USE `hotel_db`;

CREATE TABLE `role` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `value` VARCHAR(200) NOT NULL UNIQUE,
    PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    `surname` VARCHAR(200) NOT NULL,
    `email` VARCHAR(100),
    `login` VARCHAR(200) NOT NULL UNIQUE,
    `password` VARCHAR(200) NOT NULL,
    `role_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `room_type` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `value` VARCHAR(200) NOT NULL UNIQUE,
    PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `room` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `room_number` VARCHAR(200) NOT NULL UNIQUE,
    `type_id` BIGINT NOT NULL,
    `seats`TINYINT UNSIGNED NOT NULL,
    `price` DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`type_id`) REFERENCES `room_type` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `creation_date` DATETIME NOT NULL,
    `user_id` BIGINT NOT NULL,
    `room_seats`TINYINT UNSIGNED NOT NULL,
    `type_id` BIGINT NOT NULL,
    `start_date` DATE NOT NULL,
    `end_date` DATE NOT NULL,
    `room_id` BIGINT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`type_id`) REFERENCES `room_type` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`room_id`) REFERENCES `room` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;